# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance (customize the theme from data/themes)
appearance:
  theme_day: light
  theme_night: persodark
  font: custom_font
  font_size: M

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Personal page'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: xl
    show_logo: false
    show_language: false
    show_day_night: true
    show_search: false
    highlight_active_link: true

custom:
  background: img/footer.png

# Site footer

footer:
  copyright:
    notice: '© {year} Jianhui Zhang. This work is licensed under {license}.'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    #theme_light: github-light
    #theme_dark: github-dark
    #theme_light: igor
    #theme_dark: nord
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/freekatz/freekatz.github.io'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: 'giscus'
    # https://giscus.app/zh-CN
    giscus:
      repo: 'freekatz/freekatz.github.io'
      repo_id: 'R_kgDOOCgm2A'
      category: 'Announcements'
      category_id: 'DIC_kwDOOCgm2M4Cni9M'
      theme: preferred_color_scheme
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true

plugins_css: ["custom"] #,"codefolding"]

############################
## Code folding
############################

# Set to true to disable code folding
disable_codefolding: false
# Set to show to show all by default, hide to hide all by default - don't put inside quotes
codefolding_show: show
# Set to true to exclude the "Show/hide all" button
codefolding_nobutton: false
